'use client';

import { Mermaid } from './mermaid';
import schemaER from '$lib/fixtures/schema-er.mermaid?raw';
import schemaFull from '$lib/fixtures/schema.mermaid?raw';

/**
 * Simplified ER diagram showing only table relationships (no columns).
 * Useful for a high-level overview of the database structure.
 */
export function SchemaERDiagram() {
	return <Mermaid chart={schemaER} />;
}

/**
 * Full schema diagram with all columns and types.
 * Generated by tbls from the live database.
 */
export function SchemaFullDiagram() {
	return <Mermaid chart={schemaFull} />;
}
